title: Руководство
description: Описание
theme: just-the-docs

url: Rast164.github.io/Robo
logo: "/assets/images/logo.png"

callouts:
  warning:
    title: ВНИМАНИЕ
    color: red
  advice:
    title: СОВЕТ
    color: green
  note:
    title: ПРИМЕЧАНИЕ
    color: yellow
